@hostname = localhost
@port = 5090
@breweryId = 28d19840-a072-45fd-a345-a91dc030c207
@breweryStockId = 028436b8-4b63-4cf6-9b0f-b9f7745a11f1
@beerId = 7e299e74-7a51-47eb-98d0-933be4e88e7c
@wholesalerId = 03d1338b-48f2-4830-9fe6-60b3132b42f4
@wholesalerStockId = a3c59255-0d8c-44f3-9a77-89d1941ad897
@shopId = 6be7d24c-15f8-4002-ba38-c2b1cd90a239
@shopStockId = 5113d884-9d0e-49f7-95bb-1f30d7317fc1

# Get all breweries
GET http://{{hostname}}:{{port}}/api/breweries

###

# GET a specific brewery by ID
GET http://{{hostname}}:{{port}}/api/breweries/{{breweryId}}

###

# GET all brewerystocks
GET http://{{hostname}}:{{port}}/api/brewerystocks

###

# GET a specific brewerystock by ID
GET http://{{hostname}}:{{port}}/api/brewerystocks/{{breweryStockId}}

###

# GET all beers
GET http://{{hostname}}:{{port}}/api/beers

###

# GET a specific beer by ID
GET http://{{hostname}}:{{port}}/api/beers/{{beerId}}

###

# GET all wholesalers
GET http://{{hostname}}:{{port}}/api/wholesalers

###

# GET a specific wholesaler by ID
GET http://{{hostname}}:{{port}}/api/wholesalers/{{wholesalerId}}

###

# GET all wholesalerstocks
GET http://{{hostname}}:{{port}}/api/wholesalerstocks

###

# GET a specific wholesalerstock by ID
GET http://{{hostname}}:{{port}}/api/wholesalerstocks/{{wholesalerStockId}}

###

# GET all shops
GET http://{{hostname}}:{{port}}/api/shops

###

# GET a specific shop by ID
GET http://{{hostname}}:{{port}}/api/shops/{{shopId}}

###

# GET all shopstocks
GET http://{{hostname}}:{{port}}/api/shopstocks

###

# GET a specific shopstock by ID
GET http://{{hostname}}:{{port}}/api/shopstocks/{{shopStockId}}

###